body:
  - type: dropdown
    attributes:
      name: age
      label: Cachefile Age
      description: Age (in days) before the cache of calculators is refreshed.
      defaultValue: '7'
      options:
        - '1'
        - '3'
        - '5'
        - '7'
        - '10'
        - '14'
        - '21'