body:
  - type: dropdown
    attributes:
      name: age
      label: Cachefile Age
      description: Age (in days) before the cache of calculators is refreshed.
      defaultValue: '7'
      options:
        - '1'
        - '3'
        - '5'
        - '7'
        - '10'
        - '14'
        - '21'
  - type: textarea
    attributes:
      name: favourites
      label: Favourites
      description: >-
        Favourite calculators appear above all others. Add the title of the
        calculator below, separate each one by a new line.